### ISSUE TITLE
Api schemas

### ISSUE THREAD

**Issue by coreegor** [corewire/rocketbot#2]
Hello @smoehrle 
Where did you get the full description of schemas for api object types?
The original documentation at https://docs.rocket.chat/ is not clear about this.

**Comment by smoehrle** [comment]
Hey again,

unfortunately, there is/was nothing like that. It was a combination of the docs, searching in the code and trial/error. For example, [this part](https://github.com/corewire/rocketbot/blob/master/rocketbot/models/__init__.py#L90) here ensured that I got a notification, whenever they added a field to their model.

Best regards

**Comment by coreegor** [comment]
OK.
Thanks for the help.
